// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsrBINSnU39djWlTpUcuSC5C7bUdfpb5g',
    appId: '1:402886834615:web:64edf3067e09452d92d032',
    messagingSenderId: '402886834615',
    projectId: 'mouth-metrics-flutter-app',
    authDomain: 'mouth-metrics-flutter-app.firebaseapp.com',
    storageBucket: 'mouth-metrics-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_RC18ZojVZXjP1NL_4Nd2y3k0PnZZuSA',
    appId: '1:402886834615:android:1bdd70f435dffef192d032',
    messagingSenderId: '402886834615',
    projectId: 'mouth-metrics-flutter-app',
    storageBucket: 'mouth-metrics-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgqcB-osV8Sa3tBraJGNE6R65nUtAJnRc',
    appId: '1:402886834615:ios:6624524825aedf4c92d032',
    messagingSenderId: '402886834615',
    projectId: 'mouth-metrics-flutter-app',
    storageBucket: 'mouth-metrics-flutter-app.firebasestorage.app',
    iosBundleId: 'org.32studio.mouthmetrics',
  );
}
